[package]
name = "dragon_quest_dojo"
version = "0.1.0"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", rev="19293e5e065e14ecda25118b1e35a486de638fe4" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
account_address = "0x06f62894bfd81d2e396ce266b2ad0f21e0668d604e5bb1077337b6d570a54aea"
private_key = "0x07230b49615d175307d580c33d6fda61fc7b9aec91df0f5c1a5ebe3b8cbfee02"

world_address = "0x74d6cf3625879d81555bf20ee8a2273f9cc6202c13d35d71504810c14f7ef94"